# Generated by Django 3.0.8 on 2020-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
