# Generated by Django 3.0.8 on 2020-07-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=30)),
                ('p_price', models.FloatField()),
                ('p_seller', models.CharField(choices=[('Flipkart', 'Flipkart'), ('Amazon', 'Amazon'), ('Myntra', 'Mynta'), ('Ebay', 'Ebay')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Customer1')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
