# Generated by Django 3.0.8 on 2020-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20200715_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer1',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
